# build settings
gems:
  - jemoji
  - jekyll-paginate

# plugins
  - jekyll-sitemap

plugins_dir: ./_plugins

# site settings
title: "evening(code)"
description: > # this means to ignore newlines until "email:"
   늦은 밤 개발 일기

email: thn7440@gmail.com

# blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# back button
back_btn: "/assets/images/back_btn.jpg"

# author
name: 'Taeho Nam'
author: 'Taeho Nam'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://baek9.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@thnam_'

# category & tag
category_dir: category/
tag_dir: tag/

# fill in disqus shortname to use disqus
disqus: evening-code

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/thnam_
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/baek9
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
